---
collections:

- name: ansible.netcommon
- name: ansible.posix
- name: ansible.utils

- name: cisco.ios
- name: cisco.nxos
- name: cisco.ios-xr
#- name: cisco.asr
#- name: cisco.asa

- name: arista.eos
- name: junipernetworks.junos
- name: f5networks.f5_module
- name: vyos.vyos
- name: fortinet.fortios
#- name: netbox.netbox
#- name: community.routeros
#- name: infoblox.nios_modules
