---
- name: collect network device facts and running configs
  hosts: "{{ hosts | default('all') | lower }}"
  gather_facts: yes
  connection: "{{ ansible_connection | default(network_cli) }}"

  roles:
    - role: network_facts

  tasks:
    - ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is running {{ ansible_network_os }} verion {{ ansible_net_version }}"

  #- name: print ansible facts
  #  debug:
  #    var: ansible_facts

  #- name: print hostvars
  #  debug:
  #    var: hostvars
  
