---
- name: collect os facts
  hosts: "{{ hosts | default('all') | lower }}"
  gather_facts: yes
  #connection: "{{ ansible_connection | default() }}"

  tasks:
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} is running {{ ansible_distribution }}.{{ ansible_distribution_major_version }}"

    - ansible.builtin.set_fact:
        fact_inv_os_ver: "{{ inventory_hostname }}_{{ ansible_distribution }}.{{ ansible_distribution_major_version }}"

    - ansible.builtin.debug:
        var: "fact_inv_os_ver"

    #- name: print ansible facts
    #  ansible.builtin.debug:
    #    var: ansible_facts

    #- name: print hostvars
    #  ansible.builtin.debug:
    #    var: hostvars
  
