---
- name: set backup output directory - /var/tmp/backup
  file:
      path: /var/tmp/backup/
      state: directory

- name: "include {{ ansible_network_os }} tasks"
  include_tasks: "{{ ansible_network_os }}.yml"
